In [1]:
import random

a = random.random()
print(a)

0.027565243808415518


In [2]:
a = random.uniform(1, 5)
print(a)

1.683743880188989


In [3]:
a = random.randint(1, 5)
print(A)

NameError: name 'A' is not defined

In [4]:
a = random.randint(1, 5)
print(a) #In randint, the upper bound is included, i.e., here, 5 will be generated as a random number from the given range.

5


In [5]:
a = random.randrange(1, 5)
print(a) #In randrange, upper bound is not included, i.e., here, 5 will never be generated as a random number from the given range.

3


In [6]:
import random 

a = random.normalvariate(0, 1)
print(a) #This means that here, 0 is the mu or the mean and 1 is the standard deviation or sigma like in statistics.

1.189663426126371


In [7]:
import random

myList = list("ABCDEF")
print(myList)

['A', 'B', 'C', 'D', 'E', 'F']


In [8]:
a = random.choice(myList)
print(a)

D


In [9]:
a = random.sample(myList, 3)
print(a) #This will print unique samples of 3, i.e., it will never pick up a same element twice in a single sample.

['A', 'D', 'B']


In [10]:
a = random.choices(myList, k=3)
print(a) #This is same as random.sample but unlike sample, it can pick same element twice.

['F', 'E', 'A']


In [11]:
a = random.choices(myList, k=3)
print(a)

['B', 'C', 'D']


In [12]:
a = random.choices(myList, k=3)
print(a)

['A', 'F', 'C']


In [13]:
a = random.choices(myList, k=3)
print(a)

['C', 'E', 'D']


In [14]:
a = random.choices(myList, k=3)
print(a)

['F', 'B', 'C']


In [15]:
a = random.choices(myList, k=3)
print(a)

['A', 'D', 'C']


In [16]:
a = random.choices(myList, k=3)
print(a)

['D', 'C', 'A']


In [17]:
a = random.choices(myList, k=3)
print(a)

['D', 'C', 'F']


In [18]:
random.shuffle(myList)
print(myList)

['C', 'A', 'D', 'E', 'F', 'B']


In [19]:
import random

random.seed(1)
print(random.random())
print(random.randint(0, 1))

0.13436424411240122
0


In [20]:
random.seed(1)
print(random.random())
print(random.randint(0, 1)) #We can see that with random.ssed(1), the output is same for both the cells.

0.13436424411240122
0


In [21]:
#Since, random numbers are reproduceable, they cannot be used for security purposes. Therefore, in place of random, secrets module is used.
import secrets

a = secrets.randbelow(10) #Upper bound is not included.
print(a)


4


In [22]:
a = secrets.randbits(4) #here, 4 is the bits, therefore, it can provide a random number from the range 0 to 1111(in binary), i.e., 15, in decimal.
print(a)

0


In [23]:
myList = list("ABCDEF")
a = secrets.choice(myList)
print(a)

F


In [24]:
import numpy as np

In [25]:
import numpy as np

#This module is used for arrays.
a = np.random.rand(3)
print(a) #This will print a 1D array with 3 elements.

[0.32633792 0.42272091 0.58641835]


In [26]:
a = np.random.rand(3, 3)
print(a)

[[0.92535311 0.43378735 0.58623872]
 [0.02859702 0.06767788 0.23074789]
 [0.24578355 0.44432655 0.33533456]]


In [27]:
a = np.random.randint(1, 10(3, 3))
print(a)

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\PC\AppData\Local\Temp\ipykernel_7188\2229538012.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  a = np.random.randint(1, 10(3, 3))
C:\Users\PC\AppData\Local\Temp\ipykernel_7188\2229538012.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  a = np.random.randint(1, 10(3, 3))
C:\Users\PC\AppData\Local\Temp\ipykernel_7188\2229538012.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  a = np.random.randint(1, 10(3, 3))
C:\Users\PC\AppData\Local\Temp\ipykernel_7188\2229538012.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  a = np.random.randint(1, 10(3, 3))


TypeError: 'int' object is not callable

In [28]:
a = np.random.randint(1, 10,(3, 3))
print(a)

[[2 8 4]
 [5 5 8]
 [7 7 8]]


In [29]:
a = np.random.randint(1, 10, 3)
print(a)

[1 8 4]


In [30]:
arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(arr)
np.random.shuffle(arr)
print(arr)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[4, 5, 6], [1, 2, 3], [7, 8, 9]]


In [31]:
np.random.seed(1)
print(np.random.rand())
np.random.seed(1)
print(np.random.rand())

0.417022004702574
0.417022004702574


In [32]:
np.random.seed(1)
print(np.random.rand(2, 2))
np.random.seed(1)
print(np.random.rand(2, 2))

[[4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]]
[[4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]]
